### ISSUE TITLE
Update to v0.78.1

### ISSUE THREAD

**Issue by apandada1** [flathub/io.github.dosbox-staging#4]
A new version has been released. https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.78.1

**Comment by kcgen** [comment]
Thanks for this submission @apandada1 :+1: 

As a co-maintainer fo the DOSBox Staging project, I can say that the project does not have active maintainers willing to put effort into maintaining Flatpak's for the project. 

The project would be grateful if the Flathub community or anyone else wants to help.  But if that help doesn't materialize, then please consider this our request to have the outdated version taken down from Flathub, as it's causing users issues and some confusions. 

Best regards.

**Comment by Grounded0** [comment]
I'll do a 100 USD Paypal donation to anyone who updates our Flathub package to latest version.

**Comment by rderooy** [comment]
I have said to @wengier that I can do it. I already do it for DOSBox-X for the monthly releases, and have been doing it since October 2020. But I need to be give access to the project here, such that I can push changes.

Assuming I'm taken up on my offer, @Grounded0 You can give that donation to something like the EFF.

**Comment by rderooy** [comment]
I think the following needs to be done to this flatpak, if I'm not mistaken:

- Update to the latest release (0.78.1)
- Add fluidsynth
- Add libslirp

**Comment by Eonfge** [comment]
@barthalion  Somehting requiring your attention. @hfiguiere paging you since you recently merged an other pull request of mine.

The flathub package is outdated and Upstream has asked us if we can maintain it, or if we can archive it all together. Of course, it would be cool if somebody steps up to maintain the package. Better, if upstream wants to get involved directly then that would be great.

I will give it a spin but if it's to much work, then we should consider archiving instead

**Comment by rderooy** [comment]
I created a PR to update to 0.78.1 and add support for fluidsynth, libslirp and munt.
https://github.com/flathub/io.github.dosbox-staging/pull/5

**Comment by Eonfge** [comment]
@rderooy  Wow, what a timing, I just finished most of my PR. Could we combine our changes into one merge request:
https://github.com/Eonfge/io.github.dosbox-staging/commit/0f42581edbf5896649a507986d677d84a893af5f

I would recommend you to change two things;
- use static archives for downloading the packages
- use release-monitoring hooks so that Flathub can automatically create pull-requests when there are updates

It sounds like a small thing, but using anitya for dependency monitoring makes maintaining packages a lot easier.

**Comment by rderooy** [comment]
To be honest, I used git tags on purpose. Using static archives is a pita imho as I need to download the archive locally first to figure out what it's chksum is.

I'm not familiar with release-monitoring hooks, sounds like it could be useful.

In any case, I have no objections to combining efforts.

**Comment by Eonfge** [comment]
that PITA is totally understandable. I normally just write down fffffssss as sha256 so that flatpak-builder can tell me afterwards what the right sha256 is. 

This is also where the benefit of Anitya-integration will shine; It understands hashes and when a package update comes out, it will not only update the file url but also the hash. Then it creates a pull-request for easy reviewing.

**Comment by rderooy** [comment]
Just tell me how you prefer to proceed. I have no problem with you taking whatever you want from my PR and combine it into yours.

**Comment by Eonfge** [comment]
I'll be attending some other obligations this afternoon, but if you could copy-paste my sources-lists in your pull request, then we have the best of both worlds

**Comment by rderooy** [comment]
Done

**Comment by Grounded0** [comment]
Thanks! Since this is a effort of 2 individuals is it okay you both can either give your PayPal details or a link to the donation page of your choosing and i will post screenshot of when the donation was done to the non-profit. It will be 50 USD for you both.

**Comment by Grounded0** [comment]
I've now done a donation of 50 USD on behalf of @rderooy to EFF:
<img width="937" alt="Screenshot 2022-02-06 at 21 41 12" src="https://user-images.githubusercontent.com/48192273/152698521-846a3ff9-6969-4a71-b465-c3d902101979.png">

**Comment by Grounded0** [comment]
@Eonfge Can you post your PayPal details or a link to a donation page of your choosing so i can donate the 50 USD left? You can message me on Libera/EFnet/IRCnet if you want privacy on this matter (Grounded0 in all of them).

**Comment by hfiguiere** [comment]
As per #5

**Comment by Eonfge** [comment]
@hfiguiere Thanks for your lightning fast response

As for your generosity @Grounded0, I would ask you to donate it to the DOSbox Staging project: https://opencollective.com/dosbox-staging The real heroes here are people like @kcgen who build this application in the first place.

**Comment by Grounded0** [comment]
@Eonfge Done:
<img width="431" alt="Screenshot 2022-02-06 at 22 55 41" src="https://user-images.githubusercontent.com/48192273/152700973-eba82c56-1c96-4e52-a7a8-b9a504eec8fe.png">

**Comment by kcgen** [comment]
Top notch work all around 🚀 
It's an honor to be working with such a generous group!
